-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2017-04-30 21:55:28 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Detail_Hrace
  (
    dhID    INTEGER IDENTITY(1,1) NOT NULL ,
    hID     INTEGER NOT NULL ,
    rID     INTEGER ,
    p_Her   INTEGER ,
    p_Vyher INTEGER ,
    Skore INTEGER ,
    Pozice INTEGER
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Detail_Hrace__IDX ON Detail_Hrace
(
  hID
)
ON "default"
GO
ALTER TABLE Detail_Hrace ADD CONSTRAINT Detail_Hrace_PK PRIMARY KEY CLUSTERED (
dhID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Detail_tymu
  (
    dtId        INTEGER IDENTITY(1,1) NOT NULL ,
    pocet_hracu INTEGER ,
    pocet_her   INTEGER ,
    pocet_vyher INTEGER ,
    popis       VARCHAR (200) NOT NULL ,
    Pozice      INTEGER
  )
  ON "default"
GO
ALTER TABLE Detail_tymu ADD CONSTRAINT Detail_tymu_PK PRIMARY KEY CLUSTERED (
dtId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Hala_propadliku
  (
    hpID              INTEGER IDENTITY(1,1) NOT NULL ,
    hID               INTEGER NOT NULL ,
    Popis             VARCHAR (100) ,
    datum_zablokovani DATE NOT NULL ,
    doba_zablokovani  DATE NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Hala_propadliku__IDX ON Hala_propadliku
(
  hID
)
ON "default"
GO
ALTER TABLE Hala_propadliku ADD CONSTRAINT Hala_propadliku_PK PRIMARY KEY
CLUSTERED (hpID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Hrac
  (
    hID       INTEGER IDENTITY(1,1) NOT NULL ,
    lhID      INTEGER ,
    Nick_name VARCHAR (50) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Hrac ADD CONSTRAINT Hrac_PK PRIMARY KEY CLUSTERED (hID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Liga_Tymu
  (
    lID           INTEGER IDENTITY(1,1) NOT NULL ,
    Nazev_ligy    VARCHAR (50) NOT NULL ,
    Pozadavek     VARCHAR (50) NOT NULL ,
    poc_tymu      INTEGER NOT NULL ,
    status        VARCHAR (30) NOT NULL ,
    Vyhra         VARCHAR (30) NOT NULL ,
    Datum_Zacatku DATE NOT NULL ,
    Datum_Konce   DATE NOT NULL
  )
  ON "default"
GO
ALTER TABLE Liga_Tymu ADD CONSTRAINT Liga_Tymu_PK PRIMARY KEY CLUSTERED (lID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Liga_hracu
  (
    lhID          INTEGER IDENTITY(1,1) NOT NULL ,
    Nazev_ligy    VARCHAR (30) NOT NULL ,
    Pozadavek     VARCHAR (30) NOT NULL ,
    pocet_hracu   INTEGER ,
    Status        VARCHAR (50) NOT NULL ,
    Vyhra         VARCHAR (50) NOT NULL ,
    Datum_zacatku DATE NOT NULL ,
    Datum_Konce   DATE NOT NULL
  )
  ON "default"
GO
ALTER TABLE Liga_hracu ADD CONSTRAINT Liga_hracu_PK PRIMARY KEY CLUSTERED (lhID
)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Nastaveni_Hrace
  (
    setID     INTEGER IDENTITY(1,1) NOT NULL ,
    hID       INTEGER NOT NULL ,
    Jmeno     VARCHAR (50) ,
    Prijmeni  VARCHAR (50) ,
    Heslo     VARCHAR (128) NOT NULL ,
    Email     VARCHAR (50) NOT NULL ,
    Lokace    VARCHAR (50) ,
    Datum_reg DATETIME NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Nastaveni_Hrace__IDX ON Nastaveni_Hrace
(
  hID
)
ON "default"
GO
ALTER TABLE Nastaveni_Hrace ADD CONSTRAINT Nastaveni_Hrace_PK PRIMARY KEY
CLUSTERED (setID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Rank
  (
    rID   INTEGER IDENTITY(1,1) NOT NULL ,
    nazev VARCHAR (30) NOT NULL ,
    Skore INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE Rank ADD CONSTRAINT Rank_PK PRIMARY KEY CLUSTERED (rID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Tym
  (
    tID        INTEGER IDENTITY(1,1) NOT NULL ,
    lID        INTEGER ,
    dtId       INTEGER ,
    Nazev_tymu VARCHAR (30) NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Tym__IDX ON Tym
(
  dtId
)
ON "default"
GO
ALTER TABLE Tym ADD CONSTRAINT Tym_PK PRIMARY KEY CLUSTERED (tID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE TymHrac
  (
    Hrac_hID INTEGER NOT NULL ,
    Tym_tID  INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE TymHrac ADD CONSTRAINT TymHrac_PK PRIMARY KEY CLUSTERED (Hrac_hID,
Tym_tID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Zapasy_hracu
  (
    zhID         INTEGER IDENTITY(1,1) NOT NULL ,
    lhID         INTEGER NOT NULL ,
    HracA        VARCHAR (30) NOT NULL ,
    HracB        VARCHAR (30) NOT NULL ,
    SkoreA       INTEGER NOT NULL ,
    SkoreB       INTEGER NOT NULL ,
    Datum_Zapasu DATE NOT NULL
  )
  ON "default"
GO
ALTER TABLE Zapasy_hracu ADD CONSTRAINT Zapasy_hracu_PK PRIMARY KEY CLUSTERED (
zhID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE zapasy_tymu
  (
    zID         INTEGER IDENTITY(1,1) NOT NULL ,
    lID         INTEGER NOT NULL ,
    TymA        VARCHAR (50) NOT NULL ,
    TymB        VARCHAR (50) NOT NULL ,
    SkoreA      INTEGER NOT NULL ,
    SkoreB      INTEGER NOT NULL ,
    DatumZapasu DATE NOT NULL
  )
  ON "default"
GO
ALTER TABLE zapasy_tymu ADD CONSTRAINT zapasy_tymu_PK PRIMARY KEY CLUSTERED (
zID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE Detail_Hrace
ADD CONSTRAINT Detail_Hrace_Hrac_FK FOREIGN KEY
(
hID
)
REFERENCES Hrac
(
hID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Detail_Hrace
ADD CONSTRAINT Detail_Hrace_Rank_FK FOREIGN KEY
(
rID
)
REFERENCES Rank
(
rID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE TymHrac
ADD CONSTRAINT FK_ASS_20 FOREIGN KEY
(
Hrac_hID
)
REFERENCES Hrac
(
hID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE TymHrac
ADD CONSTRAINT FK_ASS_21 FOREIGN KEY
(
Tym_tID
)
REFERENCES Tym
(
tID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Hala_propadliku
ADD CONSTRAINT Hala_propadliku_Hrac_FK FOREIGN KEY
(
hID
)
REFERENCES Hrac
(
hID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Hrac
ADD CONSTRAINT Hrac_Liga_hracu_FK FOREIGN KEY
(
lhID
)
REFERENCES Liga_hracu
(
lhID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Nastaveni_Hrace
ADD CONSTRAINT Nastaveni_Hrace_Hrac_FK FOREIGN KEY
(
hID
)
REFERENCES Hrac
(
hID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tym
ADD CONSTRAINT Tym_Detail_tymu_FK FOREIGN KEY
(
dtId
)
REFERENCES Detail_tymu
(
dtId
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tym
ADD CONSTRAINT Tym_Liga_Tymu_FK FOREIGN KEY
(
lID
)
REFERENCES Liga_Tymu
(
lID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Zapasy_hracu
ADD CONSTRAINT Zapasy_hracu_Liga_hracu_FK FOREIGN KEY
(
lhID
)
REFERENCES Liga_hracu
(
lhID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE zapasy_tymu
ADD CONSTRAINT zapasy_tymu_Liga_Tymu_FK FOREIGN KEY
(
lID
)
REFERENCES Liga_Tymu
(
lID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             4
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
